export const facultyList = [
    {
        id: 1,
        name: 'Cemil Kirbas',
        status : '| Completed 1:1',
        address: '7384 Brandshire Ln Dublin, OH 43017',
        cell: '<a class="data-links" href="tel:+19376261229">(937)-626-1229</a>',
        email: '<a class="data-links" href="mailto:ckirbas1@udayton.edu>">ckirbas1@udayton.edu</a>',
        institution: 'Dayton Aug 24',
        zoom: 'DAYHS03 @shorelight.com',
        homestudio: 32,
        locationid: 249,
    },
    {
        id: 2,
        name: 'Ed Mykytka',
        status : '| Completed 1:1',
        address: '4116 Wagner Rd., Dayton, OH 45440-1427',
        cell: '<a class="data-links" href="tel:+19372722650">(937)-272-2650</a>',
        email: '<a class="data-links" href="mailto:emykytka1@udayton.edu">emykytka1@udayton.edu</a>',
        institution: 'Dayton Aug 24',
        zoom: 'DAYHS01 @shorelight.com',
        homestudio: 31,
        locationid: 238,
    },
    {
        id: 3,
        name: 'Sandy Furterer',
        status : '| Completed 1:1 (twice)',
        address: '1668 Lago Mar Dayton, OH 45458',
        cell: '<a class="data-links" href="tel:+19544159720">(954)-415-9720</a>',
        email: '<a class="data-links" href="mailto:sfurterer1@udayton.edu">sfurterer1@udayton.edu</a>',
        institution: 'Dayton Aug 24',
        zoom: 'DAYHS02 @shorelight.com',
        homestudio: 57,
        locationid: 255,
    },
    {
        id: 4,
        name: 'Tatiana Kostova',
        status : ``,
        address: '115 Brassie Court, Columbia SC 29229',
        cell: '<a class="data-links" href="tel:+18035281762">(803)-528-1762</a>',
        email: '<a class="data-links" href="mailto:kostova@moore.sc.edu">kostova@moore.sc.edu</a>',
        institution: 'South Carolina Sep 9',
        zoom: 'USCHS02 @shorelight.com',
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 5,
        name: 'Sunny Park',
        status : ``,
        address: '413 Hawkeye Ct., Columbia, SC 29206',
        cell: '<a class="data-links" href="tel:+18037305945">(803)-730-5945</a>',
        email: '<a class="data-links" href="mailto:sunny.park@moore.sc.edu">sunny.park@moore.sc.edu</a>',
        institution: 'South Carolina Sep 9',
        zoom: 'USCHS01 @shorelight.com',
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 6,
        name: 'Brynmor Thomas',
        status : '| Completed 1:1',
        address: '112 Timbergate Dr., Lexington, SC 29073',
        cell: '<a class="data-links" href="tel:+12514017730">(251)-401-7730</a>',
        email: '<a class="data-links" href="mailto:brynmor@mailbox.sc.edu">brynmor@mailbox.sc.edu</a>',
        institution: 'South Carolina Sep 9. Virtual grad Aug 31.',
        zoom: 'USCHS04 @shorelight.com',
        homestudio: 22,
        locationid: 239,
    },
    {
        id: 7,
        name: 'Jackie Woldering',
        status : ``,
        address: '8371 Twin Creek Court Mentor, OH 44060-8617',
        cell: '<a class="data-links" href="tel:+12167892483">(216)-789-2483</a>',
        email: '<a class="data-links" href="mailto:j.woldering@csuohio.edu">j.woldering@csuohio.edu</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: ``,
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 8,
        name: 'Chansu Yu',
        status : '| Dropped out',
        address: '8417 Timber Tr Brecksville, OH 44141',
        cell: '<a class="data-links" href="tel:+14406554619">(440)-655-4619</a>',
        email: '<a class="data-links" href="mailto:c.yu91@csuohio.edu">c.yu91@csuohio.edu</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: 'CSUHS01 @shorelight.com',
        homestudio: 24,
        locationid: 240,
    },
    {
        id: 9,
        name: 'Chih Hao Ku (Justin)',
        status : ``,
        address: '6572 Woodbury Dr Solon, OH 44139',
        cell: '<a class="data-links" href="tel:+1909660-0281">(909)-660-0281</a>',
        email: '<a class="data-links" href="mailto:c.ku17@csuohio.edu">c.ku17@csuohio.edu</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: ``,
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 10,
        name: 'Jingru Zhang',
        status : ``,
        address: '1701 W. Sioux Road Apt 7201, Pharr, TX 78577',
        cell: '<a class="data-links" href="tel:+14358904689">(435)-890-4689</a>',
        email: '<a class="data-links" href="mailto:jingruzhang16@gmail.com">jingruzhang16@gmail.com</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: 'CSUHS02 @shorelight.com',
        homestudio: 23,
        locationid: 242,
    },
    {
        id: 11,
        name: 'Tbd',
        status : ``,
        address: '5410 Lockwood Road, Madison Ohio, 44057',
        cell: '<a class="data-links" href="tel:+12162462963">(216)-246-2963</a>',
        email: '<a class="data-links" href="mailto:s.gubkin@csuohio.edu">s.gubkin@csuohio.edu</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: ``,
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 12,
        name: 'Abdullah Oguz',
        status : '| Completed 1:1',
        address: '1750 Ansel Rd Apt 424 Cleveland OH 44106',
        cell: '<a class="data-links" href="tel:+13368259723">(336)-825-972</a>',
        email: '<a class="data-links" href="mailto:a_oguz@uncg.edu">a_oguz@uncg.edu</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: 'CSUHS03 @shorelight.com',
        homestudio: 37,
        locationid: 243,
    },
    {
        id: 13,
        name: 'Hossein Pishro-Nik',
        status : '| Completed 1:1',
        address: '144 Plumtree Rd Sunderland, MA 01375',
        cell: '<a class="data-links" href="tel:+14136874337">(413)-687-4337</a>',
        email: '<a class="data-links" href="mailto:pishro@engin.umass.edu">pishro@engin.umass.edu</a>',
        institution: 'UMA Sep 1',
        zoom: 'UMA05 @shorelight.com',
        homestudio: 25,
        locationid: 244,
    },
    {
        id: 14,
        name: 'Wayne Burleson',
        status : '| Completed 1:1',
        address: '84 Leonard Rd, Shutesbury, MA 01072',
        cell: '<a class="data-links" href="tel:+14132304250">(413)-230-4250</a>',
        email: '<a class="data-links" href="mailto:burleson@engin.umass.edu">burleson@engin.umass.edu</a>',
        institution: 'UMA Sep 1',
        zoom: 'UMA04 @shorelight.com',
        homestudio: 30,
        locationid: 245,
    },
    {
        id: 15,
        name: 'Will Ash',
        status : '| Completed 1:1',
        address: '306 Moore Ave St Charles, IL 60174',
        cell: '<a class="data-links" href="tel:+16303098211">(630)-309-8211</a>',
        email: '<a class="data-links" href="mailto:wash@uic.edu">wash@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS08 @shorelight.com',
        homestudio: 26,
        locationid: 246,
    },
    {
        id: 16,
        name: 'Tabes Bridges',
        status : '| Completed 1:1',
        address: '2630 W. Berwyn Ave., #512 Chicago, IL 60625',
        cell: '<a class="data-links" href="tel:+13477037862">(347)-703-7862</a>',
        email: '<a class="data-links" href="mailto:mbridg5@uic.edu">mbridg5@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS09 @shorelight.com',
        homestudio: 34,
        locationid: 247,
    },
    {
        id: 17,
        name: 'Cory Davis',
        status : ``,
        address: '8047 Kildare Ave. Skokie, IL 60076',
        cell: '<a class="data-links" href="tel:+15732391932">(573)-239-1932</a>',
        email: '<a class="data-links" href="mailto:cdavis26@uic.edu">cdavis26@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS05 @shorelight.com',
        homestudio: 27,
        locationid: 248,
    },
    {
        id: 18,
        name: 'Jeffrey Schurke',
        status : '| Completed 1:1',
        address: '7010 N Ashland Blvd., Apt. 104 Chicago, IL 60626',
        cell: '<a class="data-links" href="tel:+18477215898">(847)-721-5898</a>',
        email: '<a class="data-links" href="mailto:jschuh2@uic.edu">jschuh2@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS07 @shorelight.com',
        homestudio: 33,
        locationid: 237,
    },
    {
        id: 19,
        name: 'Yuhao Chen',
        status : ``,
        address: '640 Harrison St, 1N Oak Park, IL 60304',
        cell: '<a class="data-links" href="tel:+13127217850">(312)-721-7850</a>',
        email: '<a class="data-links" href="mailto:ychen344@uic.edu">ychen344@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS01 @shorelight.com',
        homestudio: 61,
        locationid: ``,
    },
    {
        id: 20,
        name: 'Amanda Bohne',
        status : '| Completed 1:1',
        address: '2043 South Bend Ave, #373 South Bend, IN 46637',
        cell: '<a class="data-links" href="tel:+16183634532">(618)-363-4532</a>',
        email: '<a class="data-links" href="mailto:abohne@uic.edu">abohne@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS04 @shorelight.com',
        homestudio: 29,
        locationid: 251,
    },
    {
        id: 21,
        name: 'Ryan Croken',
        status : '| Completed 1:1',
        address: '1146 W. Columbia Ave., #3E Chicago, IL 60626',
        cell: '<a class="data-links" href="tel:+12243073585">(224)-307-3585</a>',
        email: '<a class="data-links" href="mailto:rcroke2@uic.edu">rcroke2@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS10 @shorelight.com',
        homestudio: 12,
        locationid: ``,
    },
    {
        id: 22,
        name: 'Rebecca Bonarek',
        status : '| Completed 1:1',
        address: '924 N. Honore St., Apt 2 Chicago, IL 60622',
        cell: '<a class="data-links" href="tel:+16302121718">(630)-212-1718</a>',
        email: '<a class="data-links" href="mailto:rbonar2@uic.edu">rbonar2@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS02 @shorelight.com',
        homestudio: 36,
        locationid: 252,
    },
    {
        id: 23,
        name: 'Jenna Buendia',
        status : '| Completed 1:1',
        address: '3329 S. Giles Ave. Chicago, IL 60616',
        cell: '<a class="data-links" href="tel:+13124152418">(312)-415-2418</a>',
        email: '<a class="data-links" href="mailto:jbuend2@uic.edu">jbuend2@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS03 @shorelight.com',
        homestudio: 35,
        locationid: 253,
    },
    {
        id: 24,
        name: 'Lin Zhu (Julie)',
        status : '| Completed 1:1',
        address: '21 Hingston Cir. Braintree, MA 02184',
        cell: '<a class="data-links" href="tel:+14698792949">(469)-879-2949</a>',
        email: '<a class="data-links" href="mailto:lin.Zhu@umb.edu">lin.Zhu@umb.edu</a>',
        institution: 'UMB- ACLive',
        zoom: 'UMBHS04 @shorelight.com',
        homestudio: 59,
        locationid: 302,
    },
    {
        id: 25,
        name: 'Luis Jimenez',
        status : ``,
        address: '47 Auburn Street Waltham, MA 02453',
        cell: '<a class="data-links" href="tel:+19282317467">(928)-231-7467</a>',
        email: '<a class="data-links" href="mailto:luis.jimenez@umb.edu">luis.jimenez@umb.edu</a>',
        institution: 'UMB- ACLive',
        zoom: ``,
        homestudio: 65,
        locationid: ``,
    },
    {
        id: 26,
        name: 'Rachel Quill',
        status : '| Completed 1:1',
        address: '3147 Sheffield Avenue Oakland, CA 94602',
        cell: '<a class="data-links" href="tel:+15103815854">(510)-381-5854</a>',
        email: '<a class="data-links" href="mailto:rachel.quill@shorelight.com">rachel.quill@shorelight.com</a>',
        institution: 'UMB- ACLive',
        zoom: 'UMBHS02 @shorelight.com',
        homestudio: 48,
        locationid: 300,
    },
    {
        id: 27,
        name: 'Jason Rickey',
        status : '| Completed 1:1',
        address: '106 Caladium Dr. Columbia, SC 29212',
        cell: '<a class="data-links" href="tel:+19376384741">(937)-638-4741</a>',
        email: '<a class="data-links" href="mailto:jason.rickey@shorelight.com">jason.rickey@shorelight.com</a>',
        institution: 'ACLive Virtual Grad',
        zoom: 'UMBHS03 @shorelight.com',
        homestudio: 54,
        locationid: 254,
    },
    {
        id: 28,
        name: 'Scott Helfgott',
        status : '| Completed 1:1',
        address: '1300 Brickell Bay Drive, Apt. 2107 Miami, Fl 33131',
        cell: '<a class="data-links" href="tel:+16466443047">(646)-644-3047</a>',
        email: '<a class="data-links" href="mailto:scott@shorelight.com">scott@shorelight.com</a>',
        institution: 'ACLive Virtual Grad',
        zoom: 'UMBHS01 @shorelight.com',
        homestudio: 60,
        locationid: 256,
    },
    {
        id: 29,
        name: 'Kui Du (Andy)',
        status : ``,
        address: '6 Heritage Drive Lexington MA, 02420',
        cell: '<a class="data-links" href="tel:+17816668073">(781)-666-8073</a>',
        email: '<a class="data-links" href="mailto:kui.du@umb.edu">kui.du@umb.edu</a>',
        institution: 'UMB ACLive MSIS 110',
        zoom: 'UMBHS08 @shorelight.com',
        homestudio: 58,
        locationid: 314,
    },
    {
        id: 30,
        name: 'Alex Kucera',
        status : '| Completed 1:1',
        address: '434 W Diversey Pkwy, apt 3C Chicago, IL 60614',
        cell: '<a class="data-links" href="tel:+17165484284">(716)-548-4284</a>',
        email: '<a class="data-links" href="mailto:alexkuc22@gmail.com">alexkuc22@gmail.com</a>',
        institution: 'UIC ECON 120',
        zoom: 'UICHS01 @shorelight.com',
        homestudio: 56,
        locationid: 257,
    },
    {
        id: 31,
        name: 'Brooke Schifano',
        status : '| Completed 1:1',
        address: '831 Cleveland St, #284 Greenville, SC, 29601',
        cell: '<a class="data-links" href="tel:+14155257687">(415)-525-7687</a>',
        email: '<a class="data-links" href="mailto:brooke.schifano001@umb.edu">brooke.schifano001@umb.edu</a>',
        institution: 'UMB ACLive',
        zoom: 'UMBHS07 @shorelight.com',
        homestudio: 55,
        locationid: 301,
    },
    {
        id: 32,
        name: 'Randall Colaizzi',
        status : ``,
        address: '8 Grant Street Unit 15 Natick, MA 01760',
        cell: '<a class="data-links" href="tel:+15082591202">(508)-259-1202</a>',
        email: '<a class="data-links" href="mailto:randall.colaizzi@umb.edu">randall.colaizzi@umb.edu</a>',
        institution: 'UMB ACLive',
        zoom: 'UMBHS06 @shorelight.com',
        homestudio: 53,
        locationid: 316,
    },
    {
        id: 33,
        name: 'Brittany Chill',
        status : ``,
        address: '2928 Hazel Ave Dayton, OH 45420',
        cell: '<a class="data-links" href="tel:+17247308809">(724)-730-8809</a>',
        email: '<a class="data-links" href="mailto:brittany.chill@udaytonglobal.org">brittany.chill@udaytonglobal.org</a>',
        institution: 'UMB MILLC 390',
        zoom: ``,
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 34,
        name: 'Jawee Perla',
        status: ``,
        address: '277 South Pickett Street, #401 Alexandria, VA 22304',
        cell: '<a class="data-links" href="tel:+12027461082">(202)-746-1082</a>',
        email: '<a class="data-links" href="mailto:jawee.perla@auaccelerator.com">jawee.perla@auaccelerator.com</a>',
        institution: 'SL Virtual Grad GCC',
        zoom: ``,
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 35,
        name: 'Mehdi Vazifedan',
        status: ``,
        address: '1429 Concord Place Drive, Apt 3B Kalamazoo MI 49009',
        cell: '<a class="data-links" href="tel:+12695699355">(269)-569-9355</a>',
        email: '<a class="data-links" href="mailto:mehdi.vazifedan@wmich.edu">mehdi.vazifedan@wmich.edu</a>',
        institution: 'UMB ACLive Math 130',
        zoom: ``,
        homestudio: 18,
        locationid: ``,
    },
    {
        id: 36,
        name: 'Kenneth Barrese',
        status: ``,
        address: '20 Radcliffe Rd. Apt 106 Boston, MA 02134',
        cell: '<a class="data-links" href="tel:+15412247889">(541)-224-7889</a>',
        email: '<a class="data-links" href="mailto:barresek@gmail.com">barresek@gmail.com</a>',
        institution: 'UMB ACLive Math 140',
        zoom: ``,
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 37,
        name: 'Charles Bartlett',
        status: ``,
        address: '227 Old Main Street Sandwich, MA 02563',
        cell: '<a class="data-links" href="tel:+13392232439">(339)-223-2439</a>',
        email: '<a class="data-links" href="mailto:bartlett.charlesf@gmail.com">bartlett.charlesf@gmail.com</a>',
        institution: 'UMB ACLive CLSCS 180',
        zoom: ``,
        homestudio: 64,
        locationid: ``,
    },
    {
        id: 38,
        name: 'Dr. Keating McKeon',
        status: ``,
        address: '1137 Massachusetts Avenue Apartment 51 Cambridge, MA 02138',
        cell: '<a class="data-links" href="tel:+18609926439">(860)-992-6439</a>',
        email: '<a class="data-links" href="mailto:keatingmckeon@fas.harvard.edu">keatingmckeon@fas.harvard.edu</a>',
        institution: 'UMB ACL CLSCS 180',
        zoom: ``,
        homestudio: 63,
        locationid: ``,
    },
    {
        id: 39,
        name: 'Perri Leviss',
        status: ``,
        address: '7 Maxfield Court Barrington, RI 02806',
        cell: '<a class="data-links" href="tel:+14015270998">(401)-527-0998</a>',
        email: '<a class="data-links" href="mailto:perri.leviss001@umb.edu">perri.leviss001@umb.edu</a>',
        institution: 'UMB ACL COMM 100',
        zoom: ``,
        homestudio: 62,
        locationid: ``,
    },
    {
        id: 40,
        name: 'Robert Reinauer',
        status: ``,
        address: '1 Hart Street Providence, RI 02906',
        cell: '<a class="data-links" href="tel:+14132046853">(413)-204-6853</a>',
        email: '<a class="data-links" href="mailto:reinauer@gmail.com">reinauer@gmail.com</a>',
        institution: 'UMB ACL ECON 120',
        zoom: ``,
        homestudio: 66,
        locationid: ``,
    },
    {
        id: 41,
        name: 'Robert Reinauer',
        status: ``,
        address: '27 Ball Rd, APT B Syracuse, NY 13215',
        cell: '<a class="data-links" href="tel:+19786044748">(978)-604-4748</a>',
        email: '<a class="data-links" href="mailto:janelle.bouzerdan001@umb.edu">janelle.bouzerdan001@umb.edu</a>',
        institution: 'UMB ACL ENGL 101',
        zoom: ``,
        homestudio: 45,
        locationid: ``,
    },
    {
        id: 42,
        name: 'Kimberly Starbuck',
        status: ``,
        address: '60 park avenue Cambridge MA 02138',
        cell: '<a class="data-links" href="tel:+16177977575">(617)-797-7575</a>',
        email: '<a class="data-links" href="mailto:kimberly.starbuck@umb.edu">kimberly.starbuck@umb.edu</a>',
        institution: 'UMB ACL ENVSTY 101',
        zoom: ``,
        homestudio: 50,
        locationid: ``,
    },
    {
        id: 43,
        name: 'Tania Konstantina Ploumi',
        status: ``,
        address: '240 Ashmont street Boston-Dorchester MA 02124',
        cell: '<a class="data-links" href="tel:+16178343472">(617)-834-3472</a>',
        email: '<a class="data-links" href="mailto:k.ploumi001@umb.edu">k.ploumi001@umb.edu</a>',
        institution: 'UMB ACL ENVSTY 101',
        zoom: ``,
        homestudio: 46,
        locationid: ``,
    },
    {
        id: 44,
        name: 'Vijaya Jyoti',
        status: ``,
        address: '159 Wharton Row Groton, MA-01450',
        cell: '<a class="data-links" href="tel:+19172076315">(917)-207-6315</a>',
        email: '<a class="data-links" href="mailto:vijaya.jyoti@umb.edu">vijaya.jyoti@umb.edu</a>',
        institution: 'UMB ACL ENVSTY 101',
        zoom: 'UMBHS30 @shorelight.com',
        homestudio: 52,
        locationid: ``,
    },
    {
        id: 45,
        name: 'Maria LaMendola',
        status: ``,
        address: ``,
        cell: '<a class="data-links" href="tel:+1"></a>',
        email: '<a class="data-links" href="mailto:maria.lamendola@umb.edu">maria.lamendola@umb.edu</a>',
        institution: 'UMB ACL ESL 100DE',
        zoom: ``,
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 46,
        name: 'Emily Bloom',
        status: ``,
        address: `416 Riegelsville Rd Milford, NJ 08848`,
        cell: '<a class="data-links" href="tel:+19084201285">(908)-420-1285</a>',
        email: '<a class="data-links" href="mailto:emily.bloom001@umb.edu">emily.bloom001@umb.edu</a>',
        institution: 'UMB ACL ESL 100DE',
        zoom: ``,
        homestudio: 49,
        locationid: ``,
    },
    {
        id: 47,
        name: 'Jamili',
        status: ``,
        address: `77 Court Street, Apt. 312 Newton, MA 02458`,
        cell: '<a class="data-links" href="tel:+16177086340">(617)-708-6340</a>',
        email: '<a class="data-links" href="mailto:emirjona.haxhimihali@umb.edu">emirjona.haxhimihali@umb.edu</a>',
        institution: 'UMB ACL ESL 100DE',
        zoom: ``,
        homestudio: 42,
        locationid: ``,
    },
    {
        id: 48,
        name: 'Michael Jacob',
        status: ``,
        address: `6 Jacobs Ave Danvers, MA 01923`,
        cell: '<a class="data-links" href="tel:+19787295708">(978)-729-5708</a>',
        email: '<a class="data-links" href="mailto:michael.jacob@umb.edu">michael.jacob@umb.edu</a>',
        institution: 'UMB ACL ESL 100DE',
        zoom: ``,
        homestudio: 43,
        locationid: ``,
    },
    {
        id: 49,
        name: 'Julia Rubin',
        status: ``,
        address: `7 Alvah Kittredge Park, Apt. 1 Boston MA 02119`,
        cell: '<a class="data-links" href="tel:+16175134995">(617)-513-4995</a>',
        email: '<a class="data-links" href="mailto:j.alexis.rubin@gmail.com">j.alexis.rubin@gmail.com</a>',
        institution: 'UMB ACL ESL 100DE',
        zoom: `UMBHS29 @shorelight.com`,
        homestudio: 51,
        locationid: ``,
    },
    {
        id: 50,
        name: 'Jamila Gilliam',
        status: ``,
        address: `200 Presidents LN Apt 15 Quincy, MA 02169`,
        cell: '<a class="data-links" href="tel:+15082321471">(508)-232-1471</a>',
        email: '<a class="data-links" href="mailto:jamila.gilliam001@umb.edu">jamila.gilliam001@umb.edu</a>',
        institution: 'UMB ACL MGT 130',
        zoom: ``,
        homestudio: 39,
        locationid: ``,
    },
    {
        id: 51,
        name: 'Qiaofeng Zhu',
        status: ``,
        address: `111 East Ave, Apt 331 Rochester, NY, 14604`,
        cell: '<a class="data-links" href="tel:+15857559106">(585)-755-9106</a>',
        email: '<a class="data-links" href="mailto:qzhu10@ur.rochester.edu">qzhu10@ur.rochester.edu</a>',
        institution: ``,
        zoom: ``,
        homestudio: 69,
        locationid: ``,
    },
    {
        id: 52,
        name: 'Theodore DeWitt',
        status: ``,
        address: `1560 Cambridge St. #3 Cambridge, MA 02139`,
        cell: '<a class="data-links" href="tel:+16462452391">(646)-245-2391</a>',
        email: '<a class="data-links" href="mailto:theodore.dewitt@umb.edu">theodore.dewitt@umb.edu</a>',
        institution: `UMB ACL MGT 130`,
        zoom: ``,
        homestudio: 47,
        locationid: ``,
    },
    {
        id: 53,
        name: 'Samaneh G. Hamidi',
        status: ``,
        address: `5 Brook St. Somerset, NJ 08873`,
        cell: '<a class="data-links" href="tel:+18017178197">(801)-717-8197</a>',
        email: '<a class="data-links" href="mailto:s.hamidi_61@yahoo.com">s.hamidi_61@yahoo.com</a>',
        institution: `UMB ACL Math 115`,
        zoom: ``,
        homestudio: 40,
        locationid: ``,
    },
    {
        id: 54,
        name: 'Chris HoehnSaric',
        status: ``,
        address: `30 concord avenue unit 2, Somerville, MA 02143`,
        cell: '<a class="data-links" href="tel:+14104090751">(410)-409-0751</a>',
        email: '<a class="data-links" href="mailto:"></a>',
        institution: `UMB ACL`,
        zoom: ``,
        homestudio: 41,
        locationid: ``,
    },
    {
        id: 55,
        name: 'Mark Kazemzadeh',
        status: ``,
        address: `21 Hingston Cir. Braintree, MA 02184`,
        cell: '<a class="data-links" href="tel:+12148681072">(214)-868-1072</a>',
        email: '<a class="data-links" href="mailto:mark.kazemzadeh@umb.edu">mark.kazemzadeh@umb.edu</a>',
        institution: `UMB ACL COMM 100`,
        zoom: ``,
        homestudio: 44,
        locationid: ``,
    },
    {
        id: 56,
        name: 'Laura Erturk',
        status: ``,
        address: `604 Mockernut Ln Columbia, SC 29209`,
        cell: '<a class="data-links" href="tel:+17044336222">(704)-433-6222</a>',
        email: '<a class="data-links" href="mailto:lauraerturk@gmail.com">lauraerturk@gmail.com</a>',
        institution: ``,
        zoom: ``,
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 57,
        name: 'Roxanne Winsor',
        status: ``,
        address: `162 Watuppa Avenue Somerset, MA 02726`,
        cell: '<a class="data-links" href="tel:+15086754539">(508)-675-4539</a>',
        email: '<a class="data-links" href="mailto:roxanne.winsor@umb.edu">roxanne.winsor@umb.edu</a>',
        institution: `UMB ACL MGT 130`,
        zoom: ``,
        homestudio: 67,
        locationid: ``,
    },
    {
        id: 58,
        name: 'Jerome Klassen',
        status: `| in Canada atm`,
        address: ``,
        cell: '<a class="data-links" href="tel:+1"></a>',
        email: '<a class="data-links" href="mailto:"></a>',
        institution: `UMB ACL PoliSci 220`,
        zoom: ``,
        homestudio: 67,
        locationid: ``,
    },
    {
        id: 59,
        name: 'Maria LaMendola',
        status: ``,
        address: `13 Ober Street Beverly MA 01915`,
        cell: '<a class="data-links" href="tel:+16174601761">(617)-460-1761</a>',
        email: '<a class="data-links" href="mailto:maria.lamendola@umb.edu">maria.lamendola@umb.edu</a>',
        institution: `UMB ACL ENGL 101`,
        zoom: ``,
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 60,
        name: 'Bao Bui',
        status: `| Completed 1:1`,
        address: `501 W. Washington St. Urbana, IL 61801`,
        cell: '<a class="data-links" href="tel:+16262134295">(626)-213-4295</a>',
        email: '<a class="data-links" href="mailto:longbui2@uic.edu">longbui2@uic.edu</a>',
        institution: `UIC-LIVE Aug 24`,
        zoom: `UICHS06 @shorelight.com`,
        homestudio: 28,
        locationid: 250,
    },
    {
        id: 61,
        name: 'Yadi Eslami',
        status: ``,
        address: `18 Grandview Street, South Hadley, MA 01075`,
        cell: '<a class="data-links" href="tel:+12089081280">(208)-908-1280</a>',
        email: '<a class="data-links" href="mailto:yeslami@umass.edu">yeslami@umass.edu</a>',
        institution: `UMA`,
        zoom: `6065983205`,
        homestudio: 10,
        locationid: 185,
    },
    {
        id: 62,
        name: 'Arman Pouraghily',
        status: ``,
        address: `54 Harley Dr., Worcester, MA 01606`,
        cell: '<a class="data-links" href="tel:+14805169997">(480)-516-9997</a>',
        email: '<a class="data-links" href="mailto:apouraghily@umass.edu">apouraghily@umass.edu</a>',
        institution: `UMA`,
        zoom: `5981156672`,
        homestudio: 11,
        locationid: 193,
    },
    {
        id: 63,
        name: 'Yusuf Mustopa',
        status: ``,
        address: `100 Rosemary Way #104 Needham Heights, MA 02494`,
        cell: '<a class="data-links" href="tel:+17189263749">(718)-926-3749</a>',
        email: '<a class="data-links" href="mailto:yusuf.mustopa@umb.edu">yusuf.mustopa@umb.edu</a>',
        institution: `UMB`,
        zoom: `5866996346`,
        homestudio: 3,
        locationid: 188,
    },
    {
        id: 64,
        name: 'Daniel Pomerleano',
        status: ``,
        address: `171 Harvard Street Apt #7 Brookline, MA 02446`,
        cell: '<a class="data-links" href="tel:+18572429498">(857)-242-9498</a>',
        email: '<a class="data-links" href="mailto:daniel.pomerleano@umb.edu">daniel.pomerleano@umb.edu</a>',
        institution: `UMB`,
        zoom: `8042082341`,
        homestudio: 4,
        locationid: 189,
    },
    {
        id: 65,
        name: 'Wenjing Liu',
        status: ``,
        address: `59 Cherry st unit 1, Cambridge, MA 02139`,
        cell: '<a class="data-links" href="tel:+18572348023">(857)-234-8023</a>',
        email: '<a class="data-links" href="mailto:wenjing.Liu@umb.edu">wenjing.Liu@umb.edu</a>',
        institution: `UMB`,
        zoom: `6803125974`,
        homestudio: 5,
        locationid: 190,
    },
    {
        id: 66,
        name: 'Christopher Rabe',
        status: ``,
        address: `4 Harley st. Dorchester MA, 02124`,
        cell: '<a class="data-links" href="tel:+18572343848">(857)-234-3848</a>',
        email: '<a class="data-links" href="mailto:christopher.rabe@umb.edu">christopher.rabe@umb.edu</a>',
        institution: `UMB`,
        zoom: `6298214698`,
        homestudio: 6,
        locationid: 191,
    },
    {
        id: 67,
        name: 'Anusha Chaitanya',
        status: ``,
        address: `70 Romsey Street, #2 Dorchester, MA 02125`,
        cell: '<a class="data-links" href="tel:+13176661368">(317)-666-1368</a>',
        email: '<a class="data-links" href="mailto:anusha.satturu001@umb.edu">anusha.satturu001@umb.edu</a>',
        institution: `UMB MGT130`,
        zoom: `5399706790`,
        homestudio: 7,
        locationid: 192,
    },
    {
        id: 68,
        name: 'Brooke Schifano',
        status: ``,
        address: `186 Sydney St, Apt 2 Boston, Ma 02125`,
        cell: '<a class="data-links" href="tel:+14155257687">(415)-525-7687</a>',
        email: '<a class="data-links" href="mailto:brooke.schifano001@umb.edu">brooke.schifano001@umb.edu</a>',
        institution: `UMB ENGL 101`,
        zoom: `2183635218`,
        homestudio: 8,
        locationid: 195,
    },
]
