export const facultyList = [
    {
        id: 1,
        name: 'Cemil Kirbas',
        status : '| Completed 1:1',
        address: '7384 Brandshire Ln Dublin, OH 43017',
        cell: '<a class="data-links" href="tel:+19376261229">(937)-626-1229</a>',
        email: '<a class="data-links" href="mailto:ckirbas1@udayton.edu>">ckirbas1@udayton.edu</a>',
        institution: 'Dayton Aug 24',
        zoom: 'DAYHS03 @shorelight.com',
        homestudio: 32,
        locationid: 249,
    },
    {
        id: 2,
        name: 'Ed Mykytka',
        status : '| Completed 1:1',
        address: '4116 Wagner Rd., Dayton, OH 45440-1427',
        cell: '<a class="data-links" href="tel:+19372722650">(937)-272-2650</a>',
        email: '<a class="data-links" href="mailto:emykytka1@udayton.edu">emykytka1@udayton.edu</a>',
        institution: 'Dayton Aug 24',
        zoom: 'DAYHS01 @shorelight.com',
        homestudio: 31,
        locationid: 238,
    },
    {
        id: 3,
        name: 'Sandy Furterer',
        status : '| Completed 1:1 (twice)',
        address: '1668 Lago Mar Dayton, OH 45458',
        cell: '<a class="data-links" href="tel:+19544159720">(954)-415-9720</a>',
        email: '<a class="data-links" href="mailto:sfurterer1@udayton.edu">sfurterer1@udayton.edu</a>',
        institution: 'Dayton Aug 24',
        zoom: 'DAYHS02 @shorelight.com',
        homestudio: 57,
        locationid: 255,
    },
    {
        id: 4,
        name: 'Tatiana Kostova',
        status : '',
        address: '115 Brassie Court, Columbia SC 29229',
        cell: '<a class="data-links" href="tel:+18035281762">(803)-528-1762</a>',
        email: '<a class="data-links" href="mailto:kostova@moore.sc.edu">kostova@moore.sc.edu</a>',
        institution: 'South Carolina Sep 9',
        zoom: 'USCHS02 @shorelight.com',
        homestudio: '',
        locationid: '',
    },
    {
        id: 5,
        name: 'Sunny Park',
        status : '',
        address: '413 Hawkeye Ct., Columbia, SC 29206',
        cell: '<a class="data-links" href="tel:+18037305945">(803)-730-5945</a>',
        email: '<a class="data-links" href="mailto:sunny.park@moore.sc.edu">sunny.park@moore.sc.edu</a>',
        institution: 'South Carolina Sep 9',
        zoom: 'USCHS01 @shorelight.com',
        homestudio: '',
        locationid: '',
    },
    {
        id: 6,
        name: 'Brynmor Thomas',
        status : '| Completed 1:1',
        address: '112 Timbergate Dr., Lexington, SC 29073',
        cell: '<a class="data-links" href="tel:+12514017730">(251)-401-7730</a>',
        email: '<a class="data-links" href="mailto:brynmor@mailbox.sc.edu">brynmor@mailbox.sc.edu</a>',
        institution: 'South Carolina Sep 9. Virtual grad Aug 31.',
        zoom: 'USCHS04 @shorelight.com',
        homestudio: 22,
        locationid: 239,
    },
    {
        id: 7,
        name: 'Jackie Woldering',
        status : '',
        address: '8371 Twin Creek Court Mentor, OH 44060-8617',
        cell: '<a class="data-links" href="tel:+12167892483">(216)-789-2483</a>',
        email: '<a class="data-links" href="mailto:j.woldering@csuohio.edu">j.woldering@csuohio.edu</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: '',
        homestudio: '',
        locationid: '',
    },
    {
        id: 8,
        name: 'Chansu Yu',
        status : '| Dropped out',
        address: '8417 Timber Tr Brecksville, OH 44141',
        cell: '<a class="data-links" href="tel:+14406554619">(440)-655-4619</a>',
        email: '<a class="data-links" href="mailto:c.yu91@csuohio.edu">c.yu91@csuohio.edu</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: 'CSUHS01 @shorelight.com',
        homestudio: 24,
        locationid: 240,
    },
    {
        id: 9,
        name: 'Chih Hao Ku (Justin)',
        status : '',
        address: '6572 Woodbury Dr Solon, OH 44139',
        cell: '<a class="data-links" href="tel:+1909660-0281">(909)-660-0281</a>',
        email: '<a class="data-links" href="mailto:c.ku17@csuohio.edu">c.ku17@csuohio.edu</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: '',
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 10,
        name: 'Jingru Zhang',
        status : '',
        address: '1701 W. Sioux Road Apt 7201, Pharr, TX 78577',
        cell: '<a class="data-links" href="tel:+14358904689">(435)-890-4689</a>',
        email: '<a class="data-links" href="mailto:jingruzhang16@gmail.com">jingruzhang16@gmail.com</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: 'CSUHS02 @shorelight.com',
        homestudio: 23,
        locationid: 242,
    },
    {
        id: 11,
        name: 'tbd',
        status : '',
        address: '5410 Lockwood Road, Madison Ohio, 44057',
        cell: '<a class="data-links" href="tel:+12162462963">(216)-246-2963</a>',
        email: '<a class="data-links" href="mailto:s.gubkin@csuohio.edu">s.gubkin@csuohio.edu</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: '',
        homestudio: ``,
        locationid: ``,
    },
    {
        id: 12,
        name: 'Abdullah Oguz',
        status : '| Completed 1:1',
        address: '1750 Ansel Rd Apt 424 Cleveland OH 44106',
        cell: '<a class="data-links" href="tel:+13368259723">(336)-825-972</a>',
        email: '<a class="data-links" href="mailto:a_oguz@uncg.edu">a_oguz@uncg.edu</a>',
        institution: 'Cleveland State University Aug 22',
        zoom: 'CSUHS03 @shorelight.com',
        homestudio: 37,
        locationid: 243,
    },
    {
        id: 13,
        name: 'Hossein Pishro-Nik',
        status : '| Completed 1:1',
        address: '144 Plumtree Rd Sunderland, MA 01375',
        cell: '<a class="data-links" href="tel:+14136874337">(413)-687-4337</a>',
        email: '<a class="data-links" href="mailto:pishro@engin.umass.edu">pishro@engin.umass.edu</a>',
        institution: 'UMA Sep 1',
        zoom: 'UMA05 @shorelight.com',
        homestudio: 25,
        locationid: 244,
    },
    {
        id: 14,
        name: 'Wayne Burleson',
        status : '| Completed 1:1',
        address: '84 Leonard Rd, Shutesbury, MA 01072',
        cell: '<a class="data-links" href="tel:+14132304250">(413)-230-4250</a>',
        email: '<a class="data-links" href="mailto:burleson@engin.umass.edu">burleson@engin.umass.edu</a>',
        institution: 'UMA Sep 1',
        zoom: 'UMA04 @shorelight.com',
        homestudio: 30,
        locationid: 245,
    },
    {
        id: 15,
        name: 'Will Ash',
        status : '| Completed 1:1',
        address: '306 Moore Ave St Charles, IL 60174',
        cell: '<a class="data-links" href="tel:+16303098211">(630)-309-8211</a>',
        email: '<a class="data-links" href="mailto:wash@uic.edu">wash@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS08 @shorelight.com',
        homestudio: 26,
        locationid: 246,
    },
    {
        id: 16,
        name: 'Tabes Bridges',
        status : '| Completed 1:1',
        address: '2630 W. Berwyn Ave., #512 Chicago, IL 60625',
        cell: '<a class="data-links" href="tel:+13477037862">(347)-703-7862</a>',
        email: '<a class="data-links" href="mailto:mbridg5@uic.edu">mbridg5@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS09 @shorelight.com',
        homestudio: 34,
        locationid: 247,
    },
    {
        id: 17,
        name: 'Cory Davis',
        status : '',
        address: '8047 Kildare Ave. Skokie, IL 60076',
        cell: '<a class="data-links" href="tel:+15732391932">(573)-239-1932</a>',
        email: '<a class="data-links" href="mailto:cdavis26@uic.edu">cdavis26@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS05 @shorelight.com',
        homestudio: 27,
        locationid: 248,
    },
    {
        id: 18,
        name: 'Jeffrey Schurke',
        status : '| Completed 1:1',
        address: '7010 N Ashland Blvd., Apt. 104 Chicago, IL 60626',
        cell: '<a class="data-links" href="tel:+18477215898">(847)-721-5898</a>',
        email: '<a class="data-links" href="mailto:jschuh2@uic.edu">jschuh2@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS07 @shorelight.com',
        homestudio: 33,
        locationid: 237,
    },
    {
        id: 19,
        name: 'Yuhao Chen',
        status : '',
        address: '640 Harrison St, 1N Oak Park, IL 60304',
        cell: '<a class="data-links" href="tel:+13127217850">(312)-721-7850</a>',
        email: '<a class="data-links" href="mailto:ychen344@uic.edu">ychen344@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS01 @shorelight.com',
        homestudio: 61,
        locationid: '',
    },
    {
        id: 20,
        name: 'Amanda Bohne',
        status : '| Completed 1:1',
        address: '2043 South Bend Ave, #373 South Bend, IN 46637',
        cell: '<a class="data-links" href="tel:+16183634532">(618)-363-4532</a>',
        email: '<a class="data-links" href="mailto:abohne@uic.edu">abohne@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS04 @shorelight.com',
        homestudio: 29,
        locationid: 251,
    },
    {
        id: 21,
        name: 'Ryan Croken',
        status : '| Completed 1:1',
        address: '1146 W. Columbia Ave., #3E Chicago, IL 60626',
        cell: '<a class="data-links" href="tel:+12243073585">(224)-307-3585</a>',
        email: '<a class="data-links" href="mailto:rcroke2@uic.edu">rcroke2@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS10 @shorelight.com',
        homestudio: 12,
        locationid: '',
    },
    {
        id: 22,
        name: 'Rebecca Bonarek',
        status : '| Completed 1:1',
        address: '924 N. Honore St., Apt 2 Chicago, IL 60622',
        cell: '<a class="data-links" href="tel:+16302121718">(630)-212-1718</a>',
        email: '<a class="data-links" href="mailto:rbonar2@uic.edu">rbonar2@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS02 @shorelight.com',
        homestudio: 36,
        locationid: 252,
    },
    {
        id: 23,
        name: 'Jenna Buendia',
        status : '| Completed 1:1',
        address: '3329 S. Giles Ave. Chicago, IL 60616',
        cell: '<a class="data-links" href="tel:+13124152418">(312)-415-2418</a>',
        email: '<a class="data-links" href="mailto:jbuend2@uic.edu">jbuend2@uic.edu</a>',
        institution: 'UIC-LIVE Aug 24',
        zoom: 'UICHS03 @shorelight.com',
        homestudio: 35,
        locationid: 253,
    },
    {
        id: 24,
        name: 'Lin Zhu (Julie)',
        status : '| Completed 1:1',
        address: '21 Hingston Cir. Braintree, MA 02184',
        cell: '<a class="data-links" href="tel:+14698792949">(469)-879-2949</a>',
        email: '<a class="data-links" href="mailto:lin.Zhu@umb.edu">lin.Zhu@umb.edu</a>',
        institution: 'UMB- ACLive',
        zoom: 'UMBHS04 @shorelight.com',
        homestudio: 59,
        locationid: 302,
    },
    {
        id: 25,
        name: 'Luis Jimenez',
        status : '',
        address: '47 Auburn Street Waltham, MA 02453',
        cell: '<a class="data-links" href="tel:+19282317467">(928)-231-7467</a>',
        email: '<a class="data-links" href="mailto:luis.jimenez@umb.edu">luis.jimenez@umb.edu</a>',
        institution: 'UMB- ACLive',
        zoom: '',
        homestudio: 65,
        locationid: '',
    },
    {
        id: 26,
        name: 'Rachel Quill',
        status : '| Completed 1:1',
        address: '3147 Sheffield Avenue Oakland, CA 94602',
        cell: '<a class="data-links" href="tel:+15103815854">(510)-381-5854</a>',
        email: '<a class="data-links" href="mailto:rachel.quill@shorelight.com">rachel.quill@shorelight.com</a>',
        institution: 'UMB- ACLive',
        zoom: 'UMBHS02 @shorelight.com',
        homestudio: 48,
        locationid: 300,
    },
    {
        id: 27,
        name: 'Jason Rickey',
        status : '| Completed 1:1',
        address: '106 Caladium Dr. Columbia, SC 29212',
        cell: '<a class="data-links" href="tel:+19376384741">(937)-638-4741</a>',
        email: '<a class="data-links" href="mailto:jason.rickey@shorelight.com">jason.rickey@shorelight.com</a>',
        institution: 'ACLive Virtual Grad',
        zoom: 'UMBHS03 @shorelight.com',
        homestudio: 54,
        locationid: 254,
    },
    {
        id: 28,
        name: 'Scott Helfgott',
        status : '| Completed 1:1',
        address: '1300 Brickell Bay Drive, Apt. 2107 Miami, Fl 33131',
        cell: '<a class="data-links" href="tel:+16466443047">(646)-644-3047</a>',
        email: '<a class="data-links" href="mailto:scott@shorelight.com">scott@shorelight.com</a>',
        institution: 'ACLive Virtual Grad',
        zoom: 'UMBHS01 @shorelight.com',
        homestudio: 60,
        locationid: 256,
    },
    {
        id: 29,
        name: 'Kui Du (Andy)',
        status : '',
        address: '6 Heritage Drive Lexington MA, 02420',
        cell: '<a class="data-links" href="tel:+17816668073">(781)-666-8073</a>',
        email: '<a class="data-links" href="mailto:kui.du@umb.edu">kui.du@umb.edu</a>',
        institution: 'UMB ACLive MSIS 110',
        zoom: 'UMBHS08 @shorelight.com',
        homestudio: 58,
        locationid: 314,
    },
    {
        id: 30,
        name: 'Alex Kucera',
        status : '| Completed 1:1',
        address: '434 W Diversey Pkwy, apt 3C Chicago, IL 60614',
        cell: '<a class="data-links" href="tel:+17165484284">(716)-548-4284</a>',
        email: '<a class="data-links" href="mailto:alexkuc22@gmail.com">alexkuc22@gmail.com</a>',
        institution: 'UIC ECON 120',
        zoom: 'UICHS01 @shorelight.com',
        homestudio: 56,
        locationid: 257,
    },
    {
        id: 31,
        name: 'Brooke Schifano',
        status : '| Completed 1:1',
        address: '831 Cleveland St, #284 Greenville, SC, 29601',
        cell: '<a class="data-links" href="tel:+14155257687">(415)-525-7687</a>',
        email: '<a class="data-links" href="mailto:brooke.schifano001@umb.edu">brooke.schifano001@umb.edu</a>',
        institution: 'UMB ACLive',
        zoom: 'UMBHS07 @shorelight.com',
        homestudio: 55,
        locationid: 301,
    },

    {
        id: 32,
        name: 'Randall Colaizzi',
        status : '',
        address: '8 Grant Street Unit 15 Natick, MA 01760',
        cell: '<a class="data-links" href="tel:+15082591202">(508)-259-1202</a>',
        email: '<a class="data-links" href="mailto:randall.colaizzi@umb.edu">randall.colaizzi@umb.edu</a>',
        institution: 'UMB ACLive',
        zoom: 'UMBHS06 @shorelight.com',
        homestudio: 53,
        locationid: 316,
    },
]
